fix(alert): fix alert ui issues
little-spoon-dev/design-system pull request #686
Opened 2022-10-26 20:00 UTC by ryanjdiercks

UI Fixes for Alert Component

## Jira

[LS-4064](https://littlespoon.atlassian.net/browse/LS-4064)

## Screenshot

![Screen Shot 2022-10-26 at 3 57 56 PM](https://user-images.githubusercontent.com/93789729/198124837-6dc8f848-d827-48f1-b1a7-ba90e35778c1.png)
![Screen Shot 2022-10-26 at 3 58 12 PM](https://user-images.githubusercontent.com/93789729/198124846-49b7f133-1c48-4aad-807f-213f636b4232.png)

2022-10-26 21:32 UTC, huhgawz requested changes

2022-10-26 21:32 UTC, huhgawz commented on packages/alert/src/AlertBase.tsx
> +  }
Something like this could be done in JSX instead:
```jsx
<Typography variant={{'0': 'p2', [breakpoints.md]: 'p3'}}>Some text</Typography>
```

2022-10-26 21:32 UTC, huhgawz commented on packages/alert/src/AlertBase.tsx
>  `
You could do something like this instead:
https://github.com/little-spoon-dev/little-spoon-frontend/blob/8b256db18696a31c36e2fe86b18a36f08776770d/app/pages/Account/MyBox/Content/ProductsGroups/ProductsGroup/styled.js#L81-L91

2022-10-26 21:32 UTC, huhgawz commented on packages/alert/src/AlertBase.tsx
>  `
Something like this could be done in JSX instead:
```jsx
<Typography variant={{'0': 'p2', [breakpoints.md]: 'p3'}}>Some text</Typography>

2022-10-26 21:36 UTC, huhgawz requested changes
Many requirements in [LS-4064](https://littlespoon.atlassian.net/browse/LS-4064) still need to be fixed:
<img width="439" src="https://user-images.githubusercontent.com/369338/198142952-1275fe45-1a91-4159-a319-cd423db24668.png">

2022-10-28 18:17 UTC, ryanjdiercks commented
> Some requirements in [LS-4064](https://littlespoon.atlassian.net/browse/LS-4064) still need to be fixed: <img alt="" width="439" src="https://user-images.githubusercontent.com/369338/198142952-1275fe45-1a91-4159-a319-cd423db24668.png">

I think I implemented these all there. 
- Developer can show/hide the close button with props.
- Implemented Toast Alert Stacking
- Increased the default Toast Alert display time to 6 secs.

and any reason why the Non Toast Alert shouldn't be animated when displayed? I couldn't find such spec in the document.

2022-10-28 22:27 UTC, huhgawz commented
> and any reason why the Non Toast Alert shouldn't be animated when displayed? I couldn't find such spec in the document.

The spec does not mention it but it feels weird, from a UX perspective, that a non toast alert is animated when displayed.  See the available component suites out there, in any of them a non toast alert is animated when displayed. For this reason I asked you to double check this behavior with Chantal

>     * Implemented Toast Alert Stacking

This image (taken from the [spec](https://zeroheight.com/3ddd0f892/p/76cbba-alert/b/70c440)) is clear about how stacking must behave:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/369338/198726923-92be3907-08f2-4874-aed8-1918c3922c19.png">

2022-11-01 16:14 UTC, huhgawz requested changes
In Storybook, Alerts with **Close** button are not being closed when the **Close** button is clicked, for example: https://deploy-preview-686--littlespoon.netlify.app/?path=/story/design-system-alert--alert-with-close. At least, generate a Storybook Action when the **Close** button is clicked

2022-11-01 16:15 UTC, huhgawz commented
> 



> > ```
> > * Implemented Toast Alert Stacking
> > ```
> 
> This image (taken from the [spec](https://zeroheight.com/3ddd0f892/p/76cbba-alert/b/70c440)) is clear about how stacking must behave:
> 
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/369338/198726923-92be3907-08f2-4874-aed8-1918c3922c19.png">
> 
> > and any reason why the Non Toast Alert shouldn't be animated when displayed? I couldn't find such spec in the document.
> 
> The spec does not mention it but it feels weird, from a UX perspective, that a non toast alert is animated when displayed. In any of the existing component suites out there (for example [MUI Alert](https://mui.com/material-ui/react-alert/#basic-alerts)) a non toast alert is animated when displayed. For this reason, I asked you to double check this behavior with Chantal

Toast-Alerts are not bumped up yet

2022-11-01 16:25 UTC, ryanjdiercks commented
> In Storybook, Alerts with **Close** button are not being closed when the **Close** button is clicked, for example: https://deploy-preview-686--littlespoon.netlify.app/?path=/story/design-system-alert--alert-with-close. At least, generate a Storybook Action when the **Close** button is clicked

@huhgawz , could you help to implement it in storybook?
The close button function should be handled in parent component and I couldn't implement it in storybook.

2022-11-01 17:54 UTC, huhgawz commented
> > In Storybook, Alerts with **Close** button are not being closed when the **Close** button is clicked, for example: https://deploy-preview-686--littlespoon.netlify.app/?path=/story/design-system-alert--alert-with-close. At least, generate a Storybook Action when the **Close** button is clicked
> 
> @huhgawz , could you help to implement it in storybook? The close button function should be handled in parent component and I couldn't implement it in storybook.

@ryanjdiercks Take a look at https://github.com/little-spoon-dev/design-system/blob/main/packages/storybook/src/stories/Drawer.stories.tsx#L12

2022-11-07 23:30 UTC, huhgawz requested changes

2022-11-07 23:30 UTC, huhgawz commented on packages/alert/src/Alert.tsx
> +    return <></>
```suggestion
    return null
```

2022-11-07 23:34 UTC, huhgawz approved these changes

2022-11-08 19:27 UTC, JenniferBrody approved these changes
QA done, design QA by Chantal too, approving

2022-11-08 20:02 UTC, merged